export const APP_LOAD = "APP_LOAD";
export const REDIRECT = "REDIRECT";
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const LOGOUT_USER = "LOGOUT_USER";
export const CLEAR_LOGOUT = "CLEAR_LOGOUT";
export const REGISTER = "REGISTER";
export const RESETPASSWORD = "RESETPASSWORD";
export const RESETLINK = "RESETLINK";
export const EMPTY_RESET_VALUE = "EMPTY_RESET_VALUE";
export const EMPTY_CHANGE_PASS_VALUE = "EMPTY_CHANGE_PASS_VALUE";
export const LOGIN_PAGE_UNLOADED = "LOGIN_PAGE_UNLOADED";
export const REGISTER_PAGE_UNLOADED = "REGISTER_PAGE_UNLOADED";
export const ASYNC_START = "ASYNC_START";
export const ASYNC_END = "ASYNC_END";
export const CURRENT_VIEW = "CURRENT_VIEW";
export const ADMIN_CHANGE_PASS = "ADMIN_CHANGE_PASS";
export const ADMIN_CLEAR_CHANGE_PASS_MESSAGES = "ADMIN_CLEAR_CHANGE_PASS_MESSAGES";
export const ALL_LOCATIONS = "ALL_LOCATIONS";
export const ADD_LOCATION = "ADD_LOCATION";
export const ADD_LOCATION_MSG_REMOVE = "ADD_LOCATION_MSG_REMOVE";
export const EDIT_LOCATION = "EDIT_LOCATION";
export const UPDATE_LOCATION = "UPDATE_LOCATION";
export const UPDATE_LOCATION_MSG_REMOVE = "UPDATE_LOCATION_MSG_REMOVE";
export const DELETE_LOCATION = "DELETE_LOCATION";
export const CLEAR_LOCATION_MSG = "DELETE_LOCATION";
export const ALL_USERS = "ALL_USERS";
export const UPDATE_FIELD_AUTH = "UPDATE_FIELD_AUTH";

export const SEND_QUERY = "SEND_QUERY";

export const ADMIN_DASHBOARD_DATA = "ADMIN_DASHBOARD_DATA";
export const ADMIN_COUPONS_DATA = "ADMIN_COUPONS_DATA";
export const AFTER_SUCCESS = "AFTER_SUCCESS";
export const RECENT_CLUB_REQUEST = "RECENT_CLUB_REQUEST";
export const FEATCH_CLUB_BY_ID = "FEATCH_CLUB_BY_ID";
export const ADMIN_PROFILE_UPDATE = "ADMIN_PROFILE_UPDATE";
export const ADMIN_CLEAR_MESSAGES = "ADMIN_CLEAR_MESSAGES";
export const STAFF_DETAIL = "STAFF_DETAIL";
export const DELETE_CLUB = "DELETE_CLUB";
export const OWNER_DASHBOARD_DATA = "OWNER_DASHBOARD_DATA";
export const PAGE_ATTR = "PAGE_ATTR";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const SAVE_SETTINGS = "SAVE_SETTINGS";
export const GET_SETTINGS = "GET_SETTINGS";
/*Admin*/
export const ALL_BUSSINESS_DATA = "ALL_BUSSINESS_DATA";
export const ALL_CUSTOMER_DATA = "ALL_CUSTOMER_DATA";
export const CLEAR_BUSINESS_MESSAGES = "CLEAR_BUSINESS_MESSAGES";
export const CREATE_BUSINESS = "CREATE_BUSINESS";
export const GET_COUPON_ADMIN = "GET_COUPON_ADMIN";
export const UPDATE_COUPON_ADMIN = "UPDATE_COUPON_ADMIN";
export const CLEAR_COUPON_MESSAGE = "CLEAR_COUPON_MESSAGE";
export const GET_BUSINESS_ADMIN = "GET_BUSINESS_ADMIN";
export const UPDATE_BUSINESS_ADMIN = "UPDATE_BUSINESS_ADMIN";
export const CLEAR_ADMIN_MESSAGE = "CLEAR_ADMIN_MESSAGE";
export const UPDATE_BUSINESS_DASH_ADMIN = "UPDATE_BUSINESS_DASH_ADMIN";
export const CLEAR_ADMIN_DASH_MESSAGE = "CLEAR_ADMIN_DASH_MESSAGE";
export const FETACH_ADMIN_FEEDBACKS_DATA = "FETACH_ADMIN_FEEDBACKS_DATA";

export const TOGGLE_BUSSINESS = "TOGGLE_BUSSINESS";
export const FETACH_ALL_PROMOCODES = "FETACH_ALL_PROMOCODES";

export const CREATE_PROMO_CODE = "CREATE_PROMO_CODE";
export const CLEAR_PROMO_CODE_MESSAGES = "CLEAR_PROMO_CODE_MESSAGES";

export const SAVE_PROMOTION_SETTING = "SAVE_PROMOTION_SETTING";
export const GET_PROMOTION_SETTING = "GET_PROMOTION_SETTING";
export const FETCH_ADMIN_PROMOTIONS = "FETCH_ADMIN_PROMOTIONS";
export const FETCH_QUERIES = "FETCH_QUERIES";
export const FETCH_QUERY = "FETCH_QUERY";
export const RESOLVE_QUERY = "RESOLVE_QUERY";
export const ADMIN_EARNING_DATA = "ADMIN_EARNING_DATA";
export const ADMIN_CHANGE_PASSWORD = "ADMIN_CHANGE_PASSWORD";
export const ADMIN_SAVE_SETTINGS = "ADMIN_SAVE_SETTINGS";
export const ADMIN_GET_NOTIFICATION_STATUS = "ADMIN_GET_NOTIFICATION_STATUS";
export const PROMOTIONS_BY_CLUB = "PROMOTIONS_BY_CLUB";
export const ADMIN_PAYMENTS_FETCH = "ADMIN_PAYMENTS_FETCH";
export const FEATCH_PAYMENT_BY_ID = "FEATCH_PAYMENT_BY_ID";


export const BROADCAST_NOTIFICATION = "BROADCAST_NOTIFICATION";
export const CLEAR_BROADCAST_NOTIFICATION = "CLEAR_BROADCAST_NOTIFICATION";

export const GET_COUPONS_BY_BUSINESS_ID = "GET_COUPONS_BY_BUSINESS_ID";
export const CANCEL_CUS_SUBSCRIPTION = "CANCEL_CUS_SUBSCRIPTION";



/*Base*/
export const FRONTEND_LOGIN = "FRONTEND_LOGIN";
export const FEATCH_CUSTOMER_PLANS = "FEATCH_CUSTOMER_PLANS";
export const CREATE_CUSTOMER = "CREATE_CUSTOMER";
export const CREATE_CUSTOMER_CLEAR_MESSAGES = "CREATE_CUSTOMER_CLEAR_MESSAGES";
export const CUSTOMER_OTP_VERIFY = "CUSTOMER_OTP_VERIFY";
export const CUSTOMER_OTP_RESEND = "CUSTOMER_OTP_RESEND";

/*Plan*/
export const PLAN_FETCH = "PLAN_FETCH";
export const PLAN_DETAIL = "PLAN_DETAIL";
export const SUBSCRIBE_PLAN = "SUBSCRIBE_PLAN";
export const CLEAR_PLAN_MESSAGE = "CLEAR_PLAN_MESSAGE";
export const CLEAR_PLAN_DATA = "CLEAR_PLAN_DATA";
export const CLEAR_MESSAGES = "CLEAR_MESSAGES";
export const CLEAR_CODE_PROMO = "CLEAR_CODE_PROMO";
export const GET_CODE_PROMO = "GET_CODE_PROMO";

/*user*/
export const GET_CUSTOMER_LOG_DETAIL = "GET_CUSTOMER_LOG_DETAIL";
export const GET_CUSTOMER_SUBSCRIPTION = "GET_CUSTOMER_SUBSCRIPTION";
export const CANCEL_CUSTOMER_SUBSCRIPTION = "CANCEL_CUSTOMER_SUBSCRIPTION";
export const CUSTOMER_PROFILE_UPDATE = "CUSTOMER_PROFILE_UPDATE";
export const SEND_FEEDBACK = "SEND_FEEDBACK";
export const CLEAR_MESSAGE_FEEDBACK = "CLEAR_MESSAGE_FEEDBACK";
export const CUSTOMER_LOGIN_TOKEN = "CUSTOMER_LOGIN_TOKEN";
export const CUSTOMER_LOGIN_TOKEN_RESET = "CUSTOMER_LOGIN_TOKEN_RESET";

/*Business*/ 
export const FEATCH_BUSINESS_PLANS = "FEATCH_BUSINESS_PLANS";
export const CREATE_BUSINESS_FRONT = "CREATE_BUSINESS_FRONT";
export const CLEAR_BUSINESS_FRONT_MESSAGES = "CLEAR_BUSINESS_FRONT_MESSAGES";
export const BUSSINESS_ALL_COUPONS = "BUSSINESS_ALL_COUPONS";
export const CREATE_COUPON = "CREATE_COUPON";
export const GET_COUPON = "GET_COUPON";
export const UPDATE_COUPON = "UPDATE_COUPON";
export const DELETE_COUPON = "DELETE_COUPON";
export const CLEAR_COUPON_MESSAGES = "CLEAR_COUPON_MESSAGES";