import React from "react";
import { MdOutlineLocationCity } from "react-icons/md";
import {
    FaUsers,
    FaTumblr,
    FaMoneyBillWaveAlt,
    FaUserTie,
} from "react-icons/fa";
import {
    MdEventAvailable,
    MdOutlineRestaurantMenu,
    MdOutlineSubscriptions,
    MdFastfood,
    MdRestaurantMenu,
} from "react-icons/md";
import { HiOutlineSpeakerphone } from "react-icons/hi";
import { GiForkKnifeSpoon, GiBackwardTime } from "react-icons/gi";
import { IoMdBowtie, IoIosUnlock } from "react-icons/io";
import { AiOutlinePullRequest, AiFillHome, AiFillCamera } from "react-icons/ai";
import { RiMessage2Fill, RiContactsBook2Line } from "react-icons/ri";
import { CgProfile } from "react-icons/cg";
import { IoIosChatbubbles } from "react-icons/io";

export const CHILD_MENU = [];

export const PRIMARY_MENU = [
    {
        id: 1,
        name: "Dashboard",
        link: "/dashboard",
        prefix: true,
        accessor: [1],
        icon: <AiFillHome />,
        iconClass: "",
        hasChild: false,
        activeLink: false,
    },
    {
        id: 2,
        name: "Profile",
        link: "/profile",
        prefix: true,
        accessor: [1],
        icon: <CgProfile />,
        iconClass: "",
        hasChild: false,
        activeLink: false,
    },
    {
        id: 3,
        name: "Businesses",
        link: "/bussinesses",
        prefix: true,
        accessor: [1],
        icon: <IoIosChatbubbles />,
        iconClass: "",
        hasChild: false,
        activeLink: false,
    },
    {
        id: 4,
        name: "Customers",
        link: "/customers",
        prefix: true,
        accessor: [1],
        icon: <IoIosChatbubbles />,
        iconClass: "",
        hasChild: false,
        activeLink: false,
    },
    {
        id: 5,
        name: "Woo-pon Requests",
        link: "/coupons",
        prefix: true,
        accessor: [1],
        icon: <IoIosChatbubbles />,
        iconClass: "",
        hasChild: false,
        activeLink: false,
    },
    {
        id: 6,
        name: "Feedback",
        link: "/feedbacks",
        prefix: true,
        accessor: [1],
        icon: <AiFillCamera />,
        iconClass: "",
        hasChild: false,
        activeLink: false,
    },
    {
        id: 7,
        name: "PromoCodes",
        link: "/promocodes",
        prefix: true,
        accessor: [1],
        icon: <MdOutlineLocationCity />,
        iconClass: "",
        hasChild: false,
        activeLink: false,
    },
    // {
    // 	id: 6,
    // 	name: 'Users',
    // 	link: '/users',
    // 	prefix: true,
    // 	accessor: [1],
    // 	icon: <FaUsers />,
    // 	iconClass: '',
    // 	hasChild: false,
    // 	activeLink: false,
    // },
    {
        id: 8,
        name: "Change Password",
        link: "null",
        prefix: true,
        accessor: [1],
        icon: <IoIosUnlock />,
        iconClass: "",
        hasChild: false,
        activeLink: false,
    },
    {
        id: 9,
        name: "Broadcast Notification",
        link: "/broadcast-notification",
        prefix: true,
        accessor: [1],
        icon: <IoIosUnlock />,
        iconClass: "",
        hasChild: false,
        activeLink: false,
    },
    // {
    // 	id: 5,
    // 	name: 'Promotions',
    // 	link: '/promotions',
    // 	prefix: true,
    // 	accessor: [1,2],
    // 	icon: <HiOutlineSpeakerphone />,
    // 	iconClass: '',
    // 	hasChild: false,
    // 	activeLink: false,
    // },
    // {
    // 	id: 6,
    // 	name: 'Promotions History',
    // 	link: '/promotions-history',
    // 	prefix: true,
    // 	accessor: [1],
    // 	icon: <GiBackwardTime />,
    // 	iconClass: '',
    // 	hasChild: false,
    // 	activeLink: false,
    // },
    // {
    // 	id: 7,
    // 	name: 'Subscriptions',
    // 	link: '#',
    // 	prefix: true,
    // 	accessor: [1],
    // 	icon: <MdOutlineSubscriptions />,
    // 	iconClass: '',
    // 	hasChild: true,
    // 	activeLink: false,
    // 	childMenus : [
    // 					{
    // 						id: 1,
    // 						name: 'Plans',
    // 						link: '/plan',
    // 						prefix: true,
    // 						accessor: [1],
    // 						icon: '',
    // 						iconClass: '',
    // 						parent: 7,
    // 						activeLink: false,
    // 					},
    // 					{
    // 						id: 2,
    // 						name: 'Features',
    // 						link: '/feature',
    // 						prefix: true,
    // 						accessor: [1],
    // 						icon: '',
    // 						iconClass: '',
    // 						parent: 7,
    // 						activeLink: false,
    // 					}
    // 				],
    // },
    // {
    // 	id: 8,
    // 	name: 'Requests',
    // 	link: '/request',
    // 	prefix: true,
    // 	accessor: [1],
    // 	icon: <AiOutlinePullRequest />,
    // 	iconClass: '',
    // 	hasChild: false,
    // 	activeLink: false,
    // },
    // {
    // 	id: 9,
    // 	name: 'Menu',
    // 	link: '/menu',
    // 	prefix: true,
    // 	accessor: [2],
    // 	icon: <MdOutlineRestaurantMenu />,
    // 	iconClass: '',
    // 	hasChild: false,
    // 	activeLink: false,
    // },
    // {
    // 	id: 10,
    // 	name: 'Staff',
    // 	link: '/staff',
    // 	prefix: true,
    // 	accessor: [2],
    // 	icon: <IoMdBowtie />,
    // 	iconClass: '',
    // 	hasChild: false,
    // 	activeLink: false,
    // },
    // {
    // 	id: 11,
    // 	name: 'Manager',
    // 	link: '/manager',
    // 	prefix: true,
    // 	accessor: [2],
    // 	icon: <FaUserTie />,
    // 	iconClass: '',
    // 	hasChild: false,
    // 	activeLink: false,
    // },
    // {
    // 	id: 12,
    // 	name: 'Queries',
    // 	link: '/queries',
    // 	prefix: true,
    // 	accessor: [1,2],
    // 	icon: <RiMessage2Fill />,
    // 	iconClass: '',
    // 	hasChild: false,
    // 	activeLink: false,
    // },
    // {
    // 	id: 13,
    // 	name: 'Contact FOMO',
    // 	link: '/contact',
    // 	prefix: true,
    // 	accessor: [2],
    // 	icon: <RiContactsBook2Line />,
    // 	iconClass: '',
    // 	hasChild: false,
    // 	activeLink: false,
    // },
    // {
    // 	id: 14,
    // 	name: 'Orders',
    // 	link: '/orders',
    // 	prefix: true,
    // 	accessor: [3],
    // 	icon: <MdFastfood />,
    // 	iconClass: '',
    // 	hasChild: false,
    // 	activeLink: false,
    // },
    // {
    // 	id: 15,
    // 	name: 'Menu',
    // 	link: '/menu',
    // 	prefix: true,
    // 	accessor: [3],
    // 	icon: <MdRestaurantMenu />,
    // 	iconClass: '',
    // 	hasChild: false,
    // 	activeLink: false,
    // },
    // {
    // 	id: 16,
    // 	name: 'Staff',
    // 	link: '/staff',
    // 	prefix: true,
    // 	accessor: [3],
    // 	icon: <IoMdBowtie />,
    // 	iconClass: '',
    // 	hasChild: false,
    // 	activeLink: false,
    // },
];
